package Enums;

public enum Commands 
{
<<<<<<< HEAD
	COMMANDS, OOC, WHO, SAY, TELL, SCORE, GIVE, GET, INVENTORY, DROP, USE, QUIT, SHUTDOWN, MOVE, LOOK, MAP, ACCEPT, DENY;
=======
	COMMANDS, OOC, WHO, SAY, TELL, SCORE, GIVE, GET, INVENTORY, DROP, USE, QUIT, SHUTDOWN, MOVE, LOOK, MAP, MOBSAY;
>>>>>>> 8aac94c4e4bcb043732acdf1d74cb1a3efca38de
}
